<?php
/**
 * XML для Polaris
 */
	$timer = microtime(1);
	$date = date('d.m.y');

	$bad_price_array = array(); // Массив в котором сохраняются адреса с плохими ценами - слишком низкие или слишком высокие от РИЦ

	
	// Загружаем файл с БД нечеткого поиска
	$objPHPExcel = PHPExcel_IOFactory::load('/var/www/reporter/settings/polaris_xml.xlsx');
/**
 * Нечёткий поиск URL NAME CODE
 */
	$sheet = $objPHPExcel->getSheet(3);
	//$qountity = $sheet->getCell( 'D1' )->getOldCalculatedValue(); // Хак для формул
	$qountity = $sheet->getHighestRow(); // Сколько строк
	echo 'Нечёткий поиск: '.$qountity.PHP_EOL;
	$data = $sheet->rangeToArray('A2:C'.$qountity);
	foreach ($data as $row) {
	  $keyURL[]  = $row[0]; // URL
	  $keyNAME[] = $row[1]; // NAME
	  $keyREALNAME[] = $row[2]; // REALNAME
	}



	/**
	 * Готовим файл Excel
	 */	
	$objPHPExcel = new PHPExcel();
	$objPHPExcel->getProperties()->setCreator("PricingLogix");
	$objPHPExcel->getProperties()->setTitle("PricingLogix");
	//$objPHPExcel->getProperties()->setSubject("PricingLogix" . ' ' . $dateHis);
	$objPHPExcel->getProperties()->setDescription("generated by PricingLogix");
	$objPHPExcel->getActiveSheet()->setTitle($datedmy.' '.ucfirst($argv[2]));	
	$objPHPExcel->getActiveSheet()->setShowGridlines(false); // Убрать сетку
	$objPHPExcel->getActiveSheet()->getSheetView()->setZoomScale(90); // Масштаб 90%
	$objPHPExcel->getDefaultStyle()->getFont()->setName('Verdana')->setSize(8); // Шрифт по умолчанию
	$objPHPExcel->getActiveSheet()->setTitle('Monitoring_WB-club');
	$objPHPExcel->getActiveSheet()->getDefaultRowDimension()->setRowHeight(10.3);


	// Вставим ЛОГОТИП
	$objDrawing = new PHPExcel_Worksheet_Drawing();
	$objDrawing->setName('Logo');
	$objDrawing->setDescription('Logo');
	$logo = AC_DIR.'/settings/logo.png'; // Provide path to your logo file
	$objDrawing->setPath($logo);
	$objDrawing->setOffsetX(1);    // setOffsetX works properly
	$objDrawing->setCoordinates('B2');
	$objDrawing->setHeight(35); // logo height
	$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());

	$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(2);			// ...отступ...
	$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(11);  	// offer id
	$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(26);		// name
	$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(30);		// model
	$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(9);			// artroz
	$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(30);		// url
	$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(9);			// shop-polaris.ru price
	$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(9);			// shop-polaris.ru Club
	$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(9);			// WB Club
/**/
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, 5, 'offer id');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, 5, 'name');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, 5, 'model');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, 5, 'artroz');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, 5, 'url');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, 5, 'shop-polaris.ru');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, 5, 'shop-polaris.ru Club');
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, 5, 'WB Club');
	//$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, 5, 'client type');
	//$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, 5, 'client price');

	

	$objPHPExcel->getActiveSheet()->getStyle("B5:CA5")->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->getStyle("B5:I5")->applyFromArray(array('borders' => array('allborders' => array(
							            					'style' => PHPExcel_Style_Border::BORDER_THIN,
							            					'color' => array('rgb' => '000000')
								            				))));

	echo 'Draw network'.PHP_EOL;
	echo microtime(1)-$timer.PHP_EOL;

/**
  * Рисуем сетку:
  */ 
	$objPHPExcel->getDefaultStyle()->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
	$objPHPExcel->getActiveSheet()->getRowDimension(5)->setRowHeight(39);
	$objPHPExcel->getActiveSheet()->getStyle('B5:DD5')->getAlignment()->setWrapText(true);
	$objPHPExcel->getActiveSheet()->getStyle('B5:DD5')->applyFromArray(
		array('alignment' => array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
															 'vertical' 	=> PHPExcel_Style_Alignment::VERTICAL_CENTER)));




/**
 * Будем открывать файл за файлом и...
 */
	$pathes = glob('/var/www/polaris/engines/*/data*/'.$date.'*polaris*moscow.data');

	$q_of_stores = count($pathes); // Общее к-во
	$istatus = 1;
	

	$allow_stores = array(
		'citilink.ru',
		'dns-shop.ru',
		'technopark.ru',
		'ozon.ru',
		'rbt.ru',
		'technopoint.ru',
		'ru.aliexpress.com',
		'komus.ru',
		'auchan.ru',
		'maxidom.ru',
		'beru.ru',
		'wildberries.ru',
		'wildberries.ru_CLUB',
		'holodilnik.ru',
		'globus.ru',
		'metro-cc.ru',
		'lenta.com',
		'goods.ru',
	);



	$except_arts = array(
		'10305506','10505426','10505428','10505427','10505425','10305505',
	);

	foreach ($pathes as $keypath) { // Перебираем каждый файлик

		system('clear');
		echo '[';
		for ($is=1; $is < $istatus*100/$q_of_stores; $is++) { 
			echo '■';	
		}
		for ($is=$istatus*100/$q_of_stores; $is <= 100; $is++) { 
			echo '.';	
		}
		echo ']'.PHP_EOL;
		$istatus++;

		preg_match("~engines/(.+)/.*polaris_(.+).data~isU", $keypath, $matches);
		$STORE = $matches[1];
		if ($STORE == 'wildberries.ru') {
			if (strripos($keypath, 'profile_polaris') !== false) {
				$STORE = 'wildberries.ru_CLUB';
			}
		}
		$CITY  = $matches[2];



		if (file_exists($keypath) && $CITY == 'moscow' && in_array($STORE, $allow_stores)) { // Если data файлик реально существует, обрабатываем его
			//echo 'Current: '.$STORE.'_'.$CITY.PHP_EOL;
			//echo $keypath.PHP_EOL;
			echo PHP_EOL.' '.$matches[1].PHP_EOL.' ';
			$current_row_array = unserialize(file_get_contents($keypath)); // Массив текущего магазина/города


			foreach ($current_row_array as $URL => $content) { // Перебираем позицию за позицией и ищем соответствия с эталонным массивом
				$key = array_search($content[0], $keyNAME);
				if ($key === false) {
					$key = array_search($URL, $keyURL);
				}
				
				$content[1] = preg_replace('~[^\d]+~', '' , $content[1]);
				if ($key !== false && $content[1] > 0) { // Ищем по URL или по NAME
					//$key = array_search($content[0], $keyNAME);
					$REALNAME = $keyREALNAME[$key];

					$V_POSITION = $priceArray[$REALNAME][0];
					$CODE 		  = substr($keyREALNAME[$key], 0, stripos($keyREALNAME[$key], '_'));
					$REALPRICE  = $priceArray[$REALNAME][2];
					$PRICE 			= $content[1];
					if (isset($keyALIAS[$CITY])) {
						$CITY_RU		= trim($keyALIAS[$CITY]);
					}
					/*
					echo '*******'.PHP_EOL;
					echo $URL.PHP_EOL;				// url
					echo $CODE.PHP_EOL;				// client CODE
					echo $REALNAME.PHP_EOL;		// client NAME
					echo $REALPRICE.PHP_EOL;	// client PRICE
					echo $PRICE.PHP_EOL;			// Store 	PRICE
					echo $CITY.PHP_EOL;				// Current City
					echo $CITY_RU.PHP_EOL;		// RU city name
					echo $STORE.PHP_EOL;			// Current Store
					echo '*******'.PHP_EOL;	
					die();
					*/


					if ($URL && $CODE && $PRICE && $STORE && $URL != 'https://www.ozon.ru/product/kupit-utyug-polaris-pir-2285k-goluboy-v-internet-magazine-ozon-tseny-otzyvy-harakteristiki-foto-173327374/'/*$REALPRICE && $PRICE && isset($STORE_ORDER[$STORE][$CITY_RU])*/) {
						$itemsArray[$CODE][$STORE] = array($URL, $PRICE);
						echo '■';
					}

				}
			}
			preg_match("~data/.*_(.+).data~isU", $keypath, $matches);
			
		}
	}

	$client_xml = new SimpleXMLElement(file_get_contents('https://shop-polaris.ru/upload/acrit.exportpro/for_parser.xml'));
	$client_xml = (array)$client_xml;

	$xml = new DomDocument('1.0','utf-8');
	$implementation = new DOMImplementation();
	$xml->appendChild($implementation->createDocumentType('yml_catalog SYSTEM "shops.dtd"'));
	$yml_catalog = $xml->appendChild($xml->createElement('yml_catalog'));
	$date = $xml->createAttribute('date');
	$date->value = date("Y-m-d H:i");
	$yml_catalog->appendChild($date);
	//$xml->appendChild($yml_catalog);
	$shop = $xml->createElement('shop');
	$yml_catalog->appendChild($shop);

	$shop->appendChild($xml->createElement('name', 'Report'));
	$shop->appendChild($xml->createElement('company', 'Pricinglogix'));
	$shop->appendChild($xml->createElement('url', 'https://pricinglogix.com/'));
	$shop->appendChild($xml->createElement('parser_end_time', date("d.m.y H:i:s", filemtime($heap_file_path)+3600))); // Разница с Москвой

	$currencies = $shop->appendChild($xml->createElement('currencies'));
	$currency = $currencies->appendChild($xml->createElement('currency'));
	$id = $xml->createAttribute('id');
	$id->value = 'RUB';
	$currency->appendChild($id);

	$offers = $shop->appendChild($xml->createElement('offers'));

	//print_r($tempHeap);
	//die();
	
	//print_r($itemsArray); die();
	//file_put_contents('/var/www/reporter/reports/polaris_xml/1.txt', print_r($itemsArray, 1));die();

	$i = 6; // Начинаем с 6-ой строки
	$client_position = array();

	$all_items_from_feed = 0;

	foreach ($client_xml[shop]->offers->offer as $val) { // Основной цикл на базе файлика клиента
		
		

		$url = trim($val->url);
		$name = trim($val->model);
		$model = trim($val->artikul);
		$price = trim($val->price);
		$price_club = trim($val->price_discount);
		$artroz = trim($val->artroz);
		$code = trim($val->axid);

		print_r($val);

		if (!in_array($artroz, $except_arts)) {

			if (count($val->axid) < 2) {
				if ($itemsArray[$code]) { // Если позиция есть в парсинге

					$all_items_from_feed++;

			
					
					// OFFER ID
					$offer = $offers->appendChild($xml->createElement('offer'));
					$offer_id = $xml->createAttribute('id');
					$offer_id->value = xml_attribute($val, 'id');//$code;///xml_attribute($val, 'axid');
					$offer->appendChild($offer_id);

					// OTHER INS OFFER
					$name = $offer->appendChild($xml->createElement('name', $name));
					$model_ins = $offer->appendChild($xml->createElement('model', $model));	
					$artroz = $offer->appendChild($xml->createElement('artroz', $artroz));	
					$url_ins = $offer->appendChild($xml->createElement('url', trim($val->url)));
					$prices = $offer->appendChild($xml->createElement('prices'));
				}
			/**
			 * EXCEL INJECTION START
			 */
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $i, xml_attribute($val, 'id')); 								// offer id
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $i, trim($val->model));		// name
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, $i, trim($val->artikul)); // model
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, $i, trim($val->artroz));	// artroz
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, $i, trim($val->url));			// url
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, $i, trim($val->price));		// price
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, $i, trim($val->price_discount));		// price club
			/**
			 * EXCEL INJECTION END
			 */

				if ($itemsArray[$code]) { // Если позиция есть в парсинге
					foreach ($itemsArray[$code] as $cl_name => $cl_value) {
						if ($cl_value[1]/trim($val->price) >= 0.5 && $cl_value[1]/trim($val->price) <= 2.5) { // Убираем цены значительно ниже и выше РИЦ
							$client = $prices->appendChild($xml->createElement('client'));
							$price = $xml->createAttribute('price');
							$price->value = $cl_value[1];
							$client->appendChild($price);

							$type = $xml->createAttribute('type');
							$type->value = $cl_name;
							$client->appendChild($type);

							$url_ins = $xml->createAttribute('url');
							$url_ins->value = $cl_value[0];
							$client->appendChild($url_ins);

							/**
							 * EXCEL INJECTION START
							 */					
							// Если это wildberries.ru_CLUB то добавляем цену в хедер
							if ($cl_name == 'wildberries.ru_CLUB') {
								$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, $i, trim($cl_value[1]));		// price wb club
							}

							if ($cl_name != 'wildberries.ru_CLUB' && $cl_name != 'shop-polaris.ru') {
								if (!in_array($cl_name, $client_position)) {
									$client_position[] = $cl_name;
									$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(count($client_position)+8, 5, $cl_name);						// type
										
									$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(count($client_position)+8, $i,'=HYPERLINK("'.$cl_value[0].'", '.$cl_value[1].')');
								} else {
									$a_key = array_search($cl_name, $client_position);
									$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($a_key+9, 5, $cl_name);						// type
											
									$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($a_key+9, $i,'=HYPERLINK("'.$cl_value[0].'", '.$cl_value[1].')');	
								}
							}
							/**
							 * EXCEL INJECTION END
							 */
						} else {
								echo 'Цена РИЦ '.$val->price.PHP_EOL;
								echo 'Цена Магазина '.$cl_value[1].PHP_EOL;
								echo 'Ссылка '.$cl_value[0].PHP_EOL;
								$bad_price_array[$cl_value[0]] = $cl_value[1];
								//sleep(3);
							}
					}
					//echo $i.' - '.trim($val->url).PHP_EOL;
										
				}
				$i++;

				
				
			} else { // Если много вариантов <axid>
				//print_r($val);


				print_r($val);
				print_r($name);

				$url = trim($val->url);
				$name = trim($val->model);
				$model = trim($val->artikul);
				$price = trim($val->price);
				$price_club = trim($val->price_discount);
				$artroz = trim($val->artroz);

				//if ($itemsArray[$code]) { // Если позиция есть в парсинге

				//}

			/**
			 * EXCEL INJECTION START
			 */
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $i, xml_attribute($val, 'id')); // offer id
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $i, trim($val->model));		// name
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, $i, trim($val->artikul)); // model
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, $i, trim($val->artroz));	// artroz
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, $i, trim($val->url));			// url
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, $i, trim($val->price));		// price
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, $i, trim($val->price_discount));		// price club
			/**
			 * EXCEL INJECTION END
			 */

				foreach ($val->axid as $axid_val) {
					$axid_val = trim($axid_val);
					echo $axid_val.PHP_EOL;

					if (@$itemsArray[$axid_val]) { // Если позиция есть в парсинге

						$all_items_from_feed++;

						// OFFER ID
						$offer = $offers->appendChild($xml->createElement('offer'));
						$offer_id = $xml->createAttribute('id');
						$offer_id->value = xml_attribute($val, 'id');///xml_attribute($val, 'axid');
						$offer->appendChild($offer_id);

						// OTHER INS OFFER
						
						$name = $offer->appendChild($xml->createElement('name', trim($val->model)));
						$model_ins = $offer->appendChild($xml->createElement('model', trim($val->artikul)));		
						$artroz = $offer->appendChild($xml->createElement('artroz', trim($val->artroz)));
						$url_ins = $offer->appendChild($xml->createElement('url', trim($val->url)));
						$prices = $offer->appendChild($xml->createElement('prices'));


						foreach ($itemsArray[$axid_val] as $cl_name => $cl_value) {
							if ($cl_value[1]/trim($val->price) >= 0.5 && $cl_value[1]/trim($val->price) <= 2.5) { // Убираем цены значительно ниже и выше РИЦ
								$client = $prices->appendChild($xml->createElement('client'));
								$price = $xml->createAttribute('price');
								$price->value = $cl_value[1];
								$client->appendChild($price);

								$type = $xml->createAttribute('type');
								$type->value = $cl_name;
								$client->appendChild($type);

								$url_ins = $xml->createAttribute('url');
								$url_ins->value = $cl_value[0];
								$client->appendChild($url_ins);

								/**
								 * EXCEL INJECTION START
								 */					
								// Если это wildberries.ru_CLUB то добавляем цену в хедер
								if ($cl_name == 'wildberries.ru_CLUB') {
									$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, $i, trim($cl_value[1]));		// price wb club
								}

								if ($cl_name != 'wildberries.ru_CLUB' && $cl_name != 'shop-polaris.ru') {
									if (!in_array($cl_name, $client_position)) {
										$client_position[] = $cl_name;
										$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(count($client_position)+8, 5, $cl_name);						// type
												
										$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(count($client_position)+8, $i,'=HYPERLINK("'.$cl_value[0].'", '.$cl_value[1].')');
									} else {
										$a_key = array_search($cl_name, $client_position);
										$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($a_key+9, 5, $cl_name);						// type
												
										$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($a_key+9, $i,'=HYPERLINK("'.$cl_value[0].'", '.$cl_value[1].')');	
									}
								}
								/**
								 * EXCEL INJECTION END
								 */
							} else {
								echo 'Цена РИЦ '.$val->price.PHP_EOL;
								echo 'Цена Магазина '.$cl_value[1].PHP_EOL;
								echo 'Ссылка '.$cl_value[0].PHP_EOL;
								$bad_price_array[$cl_value[0]] = $cl_value[1];
								//sleep(3);
							}
						}
					}
				} // Foreach axid
				
				$i++;
				
			}
		}
	}
	
	echo 'All items: '.$all_items_from_feed.PHP_EOL;

	echo 'unset $tempHeap'.PHP_EOL;
	echo microtime(1)-$timer.PHP_EOL;
	unset($tempHeap);

	echo 'data array is ready'.PHP_EOL;
	echo microtime(1)-$timer.PHP_EOL;

	$xml->save('/var/www/reporter/reports/polaris_xml/test_wbclub.xml');

	sleep(10);

	$session = ssh2_connect('en378.mirohost.net', '22');
	ssh2_auth_password($session, 'plssh', 'Cfyz13Djkrjd');
	//'/var/www/pricinglogix'
	ssh2_scp_send($session, '/var/www/reporter/reports/polaris_xml/test_wbclub.xml', '/var/www/pricinglogix/polaris.pricinglogix.com/feed/club.xml');

	file_put_contents('/var/www/reporter/reports/polaris_xml/wbclub_bad_price.txt', print_r($bad_price_array, 1));

	/**
	 * SAVING EXCEL
	 */
	$objPHPExcel->getActiveSheet()->getStyle('B5:I5')->applyFromArray(
		array('borders' => array('allborders' => array(
							            					'style' => PHPExcel_Style_Border::BORDER_MEDIUM,
							            					'color' => array('rgb' => '000000')
							            				))));
	$objPHPExcel->getActiveSheet()->setAutoFilter('B5:I5'); // Фильтры
	$objPHPExcel->getActiveSheet()->freezePane('J6');

	$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
	$objWriter->save('/var/www/reporter/reports/polaris_xml/test_wbclub.xlsx');
	ssh2_scp_send($session, '/var/www/reporter/reports/polaris_xml/test_wbclub.xlsx', '/var/www/pricinglogix/polaris.pricinglogix.com/feed/club.xlsx');


/**
 * Рассылка
 */
if (date('H') == '09') {
	$email = new PHPMailer\PHPMailer\PHPMailer();
	$email->CharSet = 'UTF-8';
	$email->IsSMTP();
	$email->Host = "mx1.mirohost.net";
	$email->Port = 25;
	$email->SMTPAuth = true;
	$email->Username = "monitoring@pricinglogix.com";
	$email->Password = "*rybuyC?D7hf";
	$email->isHTML(true);
	$email->From      = 'monitoring@pricinglogix.com';
	$email->FromName  = 'Мониторинг Цен';
	$email->Subject   = 'Рассылка club.xml, club.xlsx '.date('dmy');
	$email->AddEmbeddedImage(AC_DIR.'/settings/logo.png', 'pricinglogix-logo', 'logo.png');
	$email->Body = '<img alt="PHPMailer" src="cid:pricinglogix-logo"><br><br>лучший инструмент<br>для вашего бизнеса!<br><a href="http://pricinglogix.com/">http://pricinglogix.com</a>';

	$recipients = array(
		'Alexandr.Lisov@polaru.com',
	);
	foreach($recipients as $mailaddr) {
  	$email->AddAddress($mailaddr);
	}
	print_r($recipients);

	$recipientscopy = array(
		'alexandr.volkoff@gmail.com',
	);
	foreach($recipientscopy as $mailaddr) {
  	$email->AddCC($mailaddr);
	}

	$email->AddAttachment( '/var/www/reporter/reports/polaris_xml/test_wbclub.xml' , 'club.xml' );
	$email->AddAttachment( '/var/www/reporter/reports/polaris_xml/test_wbclub.xlsx' , 'club.xlsx' );
	

	$email->Send();
}



function xml_attribute($object, $attribute)
{
    if(isset($object[$attribute]))
        return (string) $object[$attribute];
}
